/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#191c1e",
        "on-tertiary-container": "#009668",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed-variant": "#005236",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#131b2e",
        "on-tertiary": "#ffffff",
        "outline": "#76777d",
        "on-surface-variant": "#45464d",
        "inverse-primary": "#bec6e0",
        "primary-fixed-dim": "#bec6e0",
        "secondary": "#0058be",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed-variant": "#004395",
        "tertiary-container": "#002113",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c6c6cd",
        "surface-container": "#eceef0",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadc",
        "on-error": "#ffffff",
        "on-secondary-container": "#fefcff",
        "tertiary-fixed-dim": "#4edea3",
        "on-primary-container": "#7c839b",
        "on-primary": "#ffffff",
        "surface-tint": "#565e74",
        "primary-container": "#131b2e",
        "on-tertiary-fixed": "#002113",
        "tertiary-fixed": "#6ffbbe",
        "background": "#f7f9fb",
        "on-primary-fixed-variant": "#3f465c",
        "on-surface": "#191c1e",
        "on-secondary-fixed": "#001a42",
        "primary-fixed": "#dae2fd",
        "inverse-on-surface": "#eff1f3",
        "inverse-surface": "#2d3133",
        "surface": "#f7f9fb",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container-high": "#e6e8ea",
        "surface-bright": "#f7f9fb",
        "secondary-container": "#2170e4",
        "surface-variant": "#e0e3e5",
        "tertiary": "#000000",
        "secondary-fixed": "#d8e2ff",
        "primary": "#000000",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-page": "32px",
        "gutter": "24px",
        "stack-md": "16px",
        "sidebar-width": "260px",
        "stack-sm": "8px",
        "stack-lg": "24px",
        "container-max": "1440px"
      },
      fontFamily: {
        "label-bold": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}